# Thailand Stock Trading Notebook

Welcome to the **Thailand Stock Trading Notebook** (version 1).  
This notebook is designed to help you analyze and backtest trading strategies on the Thai stock market using the powerful `ezyquant` library.

---

- 📈 **Market:** Thailand's stock
- 🛠️ **Tools:** Python, ezyquant, Jupyter Notebook
- 💡 **Purpose:** Data analysis, signal creation, and backtesting for Thai stocks

---

Let's get started and explore trading opportunities in the Thai stock market! 🚀

### First import useful library

In [1]:
!pip install ezyquant

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ezyquant in c:\users\siraw\appdata\roaming\python\python311\site-packages (0.9.6)
Requirement already satisfied: ipython in c:\programdata\anaconda3\lib\site-packages (from ezyquant) (8.12.0)
Requirement already satisfied: pandas>=1.5 in c:\programdata\anaconda3\lib\site-packages (from ezyquant) (1.5.3)
Requirement already satisfied: psycopg2-binary>=2.9 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from ezyquant) (2.9.10)
Requirement already satisfied: python-dotenv>=1.0 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from ezyquant) (1.1.0)
Requirement already satisfied: quantstats>=0.0.62 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from ezyquant) (0.0.64)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from ezyquant) (2.0.41)
Requirement already satisfied: ta>=0.10 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from ezyquant) (0.11.0)
Requirement already satisfied: typing-extensions>=4.4 in c:\programdata\anaconda3\lib\site-packages (from ezyquant) (4.6.3)
Requirement already satisfied: xlsxwriter>=3.0 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from ezyquant) (3.2.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.5->ezyquant) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.5->ezyquant) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.5->ezyquant) (1.24.3)
Requirement already satisfied: seaborn>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from quantstats>=0.0.62->ezyquant) (0.12.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from quantstats>=0.0.62->ezyquant) (3.7.1)
Requirement already satisfied: scipy>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from quantstats>=0.0.62->ezyquant) (1.10.1)
Requirement already satisfied: tabulate>=0.8.0 in c:\programdata\anaconda3\lib\site-packages (from quantstats>=0.0.62->ezyquant) (0.8.10)
Requirement already satisfied: yfinance>=0.1.70 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from quantstats>=0.0.62->ezyquant) (0.2.61)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ezyquant) (2.0.1)
Requirement already satisfied: backcall in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (0.2.0)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (0.1.6)
Requirement already satisfied: pickleshare in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (2.15.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (5.7.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython->ezyquant) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ezyquant) (0.8.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->quantstats>=0.0.62->ezyquant) (3.0.9)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython->ezyquant) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.5->ezyquant) (1.16.0)
Requirement already satisfied: requests>=2.31 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2.5.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (3.18.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (4.12.2)
Requirement already satisfied: curl_cffi>=0.7 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (0.11.1)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (6.31.1)
Requirement already satisfied: websockets>=13.0 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (15.0.1)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython->ezyquant) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython->ezyquant) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython->ezyquant) (0.2.2)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2.4)
Requirement already satisfied: cffi>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (1.15.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\siraw\appdata\roaming\python\python311\site-packages (from curl_cffi>=0.7->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2025.4.26)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (1.26.16)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance>=0.1.70->quantstats>=0.0.62->ezyquant) (2.21)

In [2]:
# import
import ezyquant as ez
from ezyquant.backtesting.account import SETAccount
from ezyquant.backtesting import Context

In [8]:
# connect to database
database_path = "C:\\Users\\siraw\\Downloads\\ezyquant\\ezyquant.db"
ez.connect_sqlite(database_path)

In [34]:
# data reader 
ssc = ez.SETSignalCreator(
   start_date="2023-01-01", # วันที่ต้องการเริ่มดึง data
   end_date="2025-06-01", # วันที่สิ้นสุดการดึง data
   index_list=['SET'], # list index ที่ต้องการจะดึงข้อมูล ถ้าไม่ต้องการให้ใส่ list ว่าง
   symbol_list= [] # list หุ้นที่ต้องการจะดึง ถ้าไม่ต้องการให้ใส่ list ว่าง
)

In [35]:
# Industry list
industry = ['AGRO','CONSUMP','FINCIAL','INDUS','PROPCON','RESOURC','SERVICE','TECH']

## First find stock before trade using net profit

In [40]:
np_df = ssc.get_data(
    field="net_profit", timeframe="quarterly" , method = "sum"
)

In [42]:
np_df

,2S,3BBIF,3K-BAT,A,A5,AAI,AAV,ACC,ACE,ACG,...,WORK,WORLD,WP,WPH,WSOL,XBIO,XPG,XYZ,ZAA,ZEN
2023-01-03,-134740000.0,NaN,79034000.0,-37071000.0,-4350410.0,195159000.0,-4.050233e+09,-12493910.0,381493380.0,5206330.0,...,65531000.0,17098930.0,46179940.0,48097000.0,5.006760e+08,-99890000.0,1431870.0,-1291000.0,5985000.0,50820000.0
2023-01-04,-134740000.0,NaN,79034000.0,-37071000.0,-4350410.0,195159000.0,-4.050233e+09,-12493910.0,381493380.0,5206330.0,...,65531000.0,17098930.0,46179940.0,48097000.0,5.006760e+08,-99890000.0,1431870.0,-1291000.0,5985000.0,50820000.0
2023-01-05,-134740000.0,NaN,79034000.0,-37071000.0,-4350410.0,195159000.0,-4.050233e+09,-12493910.0,381493380.0,5206330.0,...,65531000.0,17098930.0,46179940.0,48097000.0,5.006760e+08,-99890000.0,1431870.0,-1291000.0,5985000.0,50820000.0
2023-01-06,-134740000.0,NaN,79034000.0,-37071000.0,-4350410.0,195159000.0,-4.050233e+09,-12493910.0,381493380.0,5206330.0,...,65531000.0,17098930.0,46179940.0,48097000.0,5.006760e+08,-99890000.0,1431870.0,-1291000.0,5985000.0,50820000.0
2023-01-09,-134740000.0,NaN,79034000.0,-37071000.0,-4350410.0,195159000.0,-4.050233e+09,-12493910.0,381493380.0,5206330.0,...,65531000.0,17098930.0,46179940.0,48097000.0,5.006760e+08,-99890000.0,1431870.0,-1291000.0,5985000.0,50820000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-26,64673000.0,NaN,-85632000.0,-199762000.0,30344000.0,258647000.0,1.387226e+09,-21208000.0,226122880.0,10662880.0,...,-24106000.0,471300.0,38703220.0,178523000.0,-1.365533e+09,-62507540.0,62994780.0,-66274000.0,-8653000.0,12757000.0
2025-05-27,64673000.0,NaN,-85632000.0,-199762000.0,30344000.0,258647000.0,1.387226e+09,-21208000.0,226122880.0,10662880.0,...,-24106000.0,471300.0,38703220.0,178523000.0,-1.365533e+09,-62507540.0,62994780.0,-66274000.0,-8653000.0,12757000.0
2025-05-28,64673000.0,NaN,-85632000.0,-199762000.0,30344000.0,258647000.0,1.387226e+09,-21208000.0,226122880.0,10662880.0,...,-24106000.0,471300.0,38703220.0,178523000.0,-1.365533e+09,-62507540.0,62994780.0,-66274000.0,-8653000.0,12757000.0
2025-05-29,64673000.0,NaN,-85632000.0,-199762000.0,30344000.0,258647000.0,1.387226e+09,-21208000.0,226122880.0,10662880.0,...,-24106000.0,471300.0,38703220.0,178523000.0,-1.365533e+09,-62507540.0,62994780.0,-66274000.0,-8653000.0,12757000.0
2025-05-30,64673000.0,NaN,-85632000.0,-199762000.0,30344000.0,258647000.0,1.387226e+09,-21208000.0,226122880.0,10662880.0,...,-24106000.0,471300.0,38703220.0,178523000.0,-1.365533e+09,-62507540.0,62994780.0,-66274000.0,-8653000.0,12757000.0

In [45]:
np_df.index

DatetimeIndex(['2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-16',
               ...
               '2025-05-19', '2025-05-20', '2025-05-21', '2025-05-22',
               '2025-05-23', '2025-05-26', '2025-05-27', '2025-05-28',
               '2025-05-29', '2025-05-30'],
              dtype='datetime64[ns]', length=587, freq=None)

In [46]:
np_df.columns

Index(['2S', '3BBIF', '3K-BAT', 'A', 'A5', 'AAI', 'AAV', 'ACC', 'ACE', 'ACG',
       ...
       'WORK', 'WORLD', 'WP', 'WPH', 'WSOL', 'XBIO', 'XPG', 'XYZ', 'ZAA',
       'ZEN'],
      dtype='object', length=745)

In [47]:
import pandas as pd
import numpy as np

In [51]:
np_df_t = np_df.T
np_df_t

,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-16,...,2025-05-19,2025-05-20,2025-05-21,2025-05-22,2025-05-23,2025-05-26,2025-05-27,2025-05-28,2025-05-29,2025-05-30
2S,-134740000.0,-134740000.0,-134740000.0,-134740000.0,-134740000.0,-134740000.0,-134740000.0,-134740000.0,-134740000.0,-134740000.0,...,64673000.0,64673000.0,64673000.0,64673000.0,64673000.0,64673000.0,64673000.0,64673000.0,64673000.0,64673000.0
3BBIF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3K-BAT,79034000.0,79034000.0,79034000.0,79034000.0,79034000.0,79034000.0,79034000.0,79034000.0,79034000.0,79034000.0,...,-85632000.0,-85632000.0,-85632000.0,-85632000.0,-85632000.0,-85632000.0,-85632000.0,-85632000.0,-85632000.0,-85632000.0
A,-37071000.0,-37071000.0,-37071000.0,-37071000.0,-37071000.0,-37071000.0,-37071000.0,-37071000.0,-37071000.0,-37071000.0,...,-199762000.0,-199762000.0,-199762000.0,-199762000.0,-199762000.0,-199762000.0,-199762000.0,-199762000.0,-199762000.0,-199762000.0
A5,-4350410.0,-4350410.0,-4350410.0,-4350410.0,-4350410.0,-4350410.0,-4350410.0,-4350410.0,-4350410.0,-4350410.0,...,30344000.0,30344000.0,30344000.0,30344000.0,30344000.0,30344000.0,30344000.0,30344000.0,30344000.0,30344000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XBIO,-99890000.0,-99890000.0,-99890000.0,-99890000.0,-99890000.0,-99890000.0,-99890000.0,-99890000.0,-99890000.0,-99890000.0,...,-62507540.0,-62507540.0,-62507540.0,-62507540.0,-62507540.0,-62507540.0,-62507540.0,-62507540.0,-62507540.0,-62507540.0
XPG,1431870.0,1431870.0,1431870.0,1431870.0,1431870.0,1431870.0,1431870.0,1431870.0,1431870.0,1431870.0,...,62994780.0,62994780.0,62994780.0,62994780.0,62994780.0,62994780.0,62994780.0,62994780.0,62994780.0,62994780.0
XYZ,-1291000.0,-1291000.0,-1291000.0,-1291000.0,-1291000.0,-1291000.0,-1291000.0,-1291000.0,-1291000.0,-1291000.0,...,-66274000.0,-66274000.0,-66274000.0,-66274000.0,-66274000.0,-66274000.0,-66274000.0,-66274000.0,-66274000.0,-66274000.0
ZAA,5985000.0,5985000.0,5985000.0,5985000.0,5985000.0,5985000.0,5985000.0,5985000.0,5985000.0,5985000.0,...,-8653000.0,-8653000.0,-8653000.0,-8653000.0,-8653000.0,-8653000.0,-8653000.0,-8653000.0,-8653000.0,-8653000.0
ZEN,50820000.0,50820000.0,50820000.0,50820000.0,50820000.0,50820000.0,50820000.0,50820000.0,50820000.0,50820000.0,...,17865000.0,12757000.0,12757000.0,12757000.0,12757000.0,12757000.0,12757000.0,12757000.0,12757000.0,12757000.0

In [56]:
new_df = pd.DataFrame(index = np_df_t.index)
new_df['Q1 2024'] = np_df_t['2024-03-25']
new_df['Q1 2025'] = np_df_t['2025-03-25']
new_df.dropna()

            Q1 2024      Q1 2025
2S       17353000.0    9518000.0
3K-BAT  -23401000.0  -85632000.0
A      -122109060.0 -211447650.0
A5      158709740.0  -35614650.0
AAI     166190280.0  172528340.0
...             ...          ...
XBIO    -64885430.0 -134819620.0
XPG      34144780.0   46132680.0
XYZ      43259590.0  -28967160.0
ZAA     -53958390.0  -88732870.0
ZEN      37821000.0   17865000.0

[651 rows x 2 columns]

In [71]:
new_df['%_change'] = (new_df['Q1 2025'] - new_df['Q1 2024'])/new_df['Q1 2024']
new_df = new_df.dropna()
new_df

            Q1 2024      Q1 2025  %_change
2S       17353000.0    9518000.0 -0.451507
3K-BAT  -23401000.0  -85632000.0  2.659331
A      -122109060.0 -211447650.0  0.731629
A5      158709740.0  -35614650.0 -1.224401
AAI     166190280.0  172528340.0  0.038137
...             ...          ...       ...
XBIO    -64885430.0 -134819620.0  1.077810
XPG      34144780.0   46132680.0  0.351090
XYZ      43259590.0  -28967160.0 -1.669612
ZAA     -53958390.0  -88732870.0  0.644468
ZEN      37821000.0   17865000.0 -0.527643

[651 rows x 3 columns]

## Next, We will find the industry of each stock

In [80]:
pe_industry_df = ssc.get_data(
    field="mkt_pe", timeframe="daily", value_by="industry"
)
pe_industry_df = pe_industry_df.T['2023-01-03'].dropna()
pe_industry_df.columns = ['symbol', 'pe']
pe_industry_df.head(30)

2S        12.43
3BBIF     44.72
3K-BAT    12.43
A         17.56
A5        17.56
AAI       17.19
AAV       38.46
ACC       11.68
ACE       11.68
ACG       12.43
ADVANC    44.72
ADVICE    38.46
AE        11.68
AEONTS    13.34
AFC       13.89
AGE       11.68
AH        12.43
AHC       38.46
AI        11.68
AIE       11.68
AIMCG     17.56
AIMIRT    17.56
AIT       44.72
AJ        12.43
AJA       13.89
AKR       12.43
AKS       17.56
ALLA      12.43
ALLY      17.56
ALT       44.72
Name: 2023-01-03 00:00:00, dtype: float64

In [81]:
def show_industry(pe):
    if pe == 12.43 :
        return 'INDUS'
    elif pe == 44.72:
        return 'TECH'
    elif pe == 17.56:
        return 'PROPCON'
    elif pe == 17.19:
        return 'HEALTH'
    elif pe == 38.46:
        return 'SERVICE'
    elif pe == 11.68:
        return 'ENERG'
    elif pe == 13.34:
        return 'FINC'
    elif pe == 13.89:
        return 'AGRO'

In [ ]:
# new_df['industry'] = new_df.index.apply(show_industry)

AttributeError: 'Index' object has no attribute 'apply'